version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    volumes:
      - ./.pgdata/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: realpassword
      POSTGRES_DB: local
    ports:
      - "54321:5432"
    healthcheck:  # Check that we can log into our database
      test: [ "CMD-SHELL", "pg_isready -U chris -d local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    build:
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/api/app/
    ports:
      - "5001:5000"
    tty: true
    stdin_open: true
    environment:
      ENV: "LOCAL"
    depends_on:
      db:
        condition: service_healthy
